---
title: All-In Hosts Opinion on Jobs
date: '2023-06-10'
author: Lawrence Wu
categories: [ai, career]
---

During [Episode 132 of the All-In Podcast](https://www.youtube.com/watch?v=aPMNbMR1p70&ab_channel=All-InPodcast), (transcript [here](https://steno.ai/all-in-with-chamath-jason-sacks/e132-sec-goes-after-crypto-giants-sequoia-splits-livpga-messis)) the hosts took a live question from the audience:

{{< video https://www.youtube.com/embed/aPMNbMR1p70 >}}

> Hi, I'm Jeff, a full-time corporate VC and part-time angel. My question is about AI and higher education and it's actually some covert parenting advice so you can decide who's that's relevant for. My son just finished his freshman year of college and I'm questioning what the future is for him in higher education, given all the change that AI is going to have on every career and every profession. And I'm wondering what advice you'd give to your child or someone who's in college right now for what's an area of study that maybe won't be disrupted by AI or an area that AI, you'll get leverage from your education through AI.

Chamath:

> I think the reality is that most of the existing jobs that we have in the United States are going to go to lower cost locations that have that tool chain to accelerate their capability. So we are going to have to reinvent the workforce and the things that we do over the next 30 or 40 years to stay relevant. That's probably like, I think that should just be the operating principle. If you think about it, we used to run great call centers. Okay, those call centers were outsourced to the Philippines and India. But in the next, you know, five or 10 years, you'll have this flawless unaccented English or even more eerily, perfectly accented English for the zip code of the person that's calling in so that it sounds like they're talking to somebody that's literally their neighbor. That's like just makes so much sense, right? So it's like all this stuff is going to happen where like all these classes of jobs are going to go away. I saw this article where a lawyer, two lawyers use chat GPT to submit a legal brief. The problem was that it cited cases that didn't exist and now they're going to be disbarred. So this is like serious business, right? Like you can't do that.

> You know, if I had to choose something for my kids, I would probably, I would probably tell them to do something mathematical or biological.

Jason:

> I've been thinking about this a lot too. I think teaching them to be entrepreneurial, resilient, worldly, ability to communicate, ability to lead other people in teams, that stuff's not going to go away, communication skill, etc. I'm encouraging everybody who I work with to just use chat GPT-4 and Bard every day for every single thing that they do. My base thesis right now is that the job freezes, the hiring freezes out of all these companies is indefinite. I'm assuming it's indefinite because the amount of work it takes to write a job requisition is more work in some cases than actually automating with AI or ready the job function. And so I think 20 person companies might double in size in the next two or three years, but still have 20 people. This is going to be a big challenge for society. And if that does come to pass, there's just going to be large swaths of people who are not going to be able to get job interviews for anything other than service jobs. We need a lot more plumbers, electricians, waiters, et cetera. Those probably jobs won't go away, especially if we don't let people immigrate. I am super enthusiastic about that efficiency, but I think it also means you have to be entrepreneurial because if you can't get a job and you can't get mentored, you better create your own opportunity. You better create your own company. And that's what I'm seeing. That's the game on the field right now. Two or three people who don't have job offers from Uber and Airbnb and Google and Facebook just saying, let's start a company because there's nothing else for us to do. And those are highly skilled people right now doing that.

Sacks:

> I'll say two quick things about this topic. So one is, I think there's a lot of AI fear porn out there right now. And I just think that like all of these tumor scenarios are, they're not going to play out overnight. I mean, this is going to take a while. Second, if you think about like job elimination, it's going to be some super specialized jobs. So for example, I wouldn't want to be a radiologist right now, but doctors will be fine. So I think if you're thinking about like going into a job category that's super specialized and clearly in the way of AI, then that probably is not a good idea. But most general skills like you're talking about and most job categories are going to be fine. There's just going to be some specialties within them that make it. dislocated. Like, I wouldn't want to be a truck driver either, you know, because of self-driving. But transportation companies are still going to exist. So I think you just want to be careful about super specialization, I think. But building general skills is always really good. That really should be the point of college.

My observations:

- I found it surprising Sacks thought lawyers and accountants were "sufficiently" general that he doesn't think they'll be eliminated.
- Sacks' point that some super specialized jobs will be eliminated is a good one, e.g. radiologists. But I also think some lawyers and accounting jobs will go this route too.
- Jason is telling his employees to use GPT-4 or Bard for every task at work. I agree this is a good idea to get familiar with how LLMs work and to essentially have a super-assistant at your disposal. GPT-4 is particularly good.
- Overall I think it's still too early to make any definitive statements about what jobs will be eliminated. I think it's safe to say that most jobs will be affected in some way, but it's hard to say how. This is something I'm fascinated by though, how as a society we will adjust as these language models permeate through organizations, companies and products.
