---
title: "GPT Related Papers, Code, and News"
date: "2023-04-04"
author: "Lawrence Wu"
categories: ["GPT", "OpenAI"]
---

There's seemingly a firehose of development in the last month or so. I've been trying to keep up with the latest developments in GPT and related models. Here's a list of papers, code, and news that I've found interesting. This is mainly for myself to have a reference, but I hope it's useful to others as well. I was largely inspired by [@osanseviero](https://twitter.com/osanseviero) who created [ml_timeline](https://github.com/osanseviero/ml_timeline).

# Papers
- 2022-08-21 - Emergent Abilities of Large Language Models ([paper](https://openreview.net/forum?id=yzkSU5zdwD), [blog](https://ai.googleblog.com/2022/11/characterizing-emergent-phenomena-in.html))
- 2023-03-13 - [Alpaca](https://crfm.stanford.edu/2023/03/13/alpaca.html) – Stanford’s CRFM group released a 1.5B parameter GPT-3 like model. They were the first to demonstrate you can get GPT-like performance using only 52k instruction-following data points. On the self-instruct evaluation set, Alpaca shows many behaviors similar to OpenAI’s text-davinci-003, but is also surprisingly small and easy/cheap to reproduce. I think one reason OpenAI dropped their pricing by 90% with GPT-4 is because they wanted to achieve wide distribution of their model.
- 2023-03-15 - GPT-4 Technical Paper ([paper](https://arxiv.org/abs/2303.08774)) - highlights some of the amazing improvements GPT-4 has made over GPT-3
- 2023-03-27 - GPTs are GPTs: An Early Look at the Labor Market Impact Potential of Large Language Models ([paper](https://arxiv.org/pdf/2303.10130.pdf)) – Paper that identifies the occupations that have the highest exposure to automation by GPT. In related news, ResumeBuilder found [1 in 4 companies have already replaced workers with ChatGPT](https://www.resumebuilder.com/1-in-4-companies-have-already-replaced-workers-with-chatgpt/#:~:text=With%20the%20emergence%20of%20ChatGPT,%2C%20write%20code%2C%20and%20more)
- 2023-03-22 - Sparks of Artificial General Intelligence ([paper](https://arxiv.org/abs/2303.12712))
- 2023-03-20 – Reflexion: an autonomous agent with dynamic memory and self-reflection ([paper](https://arxiv.org/abs/2303.11366)). A related [post](https://nanothoughts.substack.com/p/reflecting-on-reflexion).
- 2023-03-23 - AI Explained – GPT4 can improve itself ([video](https://www.youtube.com/watch?v=5SgJKZLBrmg&ab_channel=AIExplained)) - Intro to Reflexion and HuggingGPT
- 2023-03-30 - HuggingGPT: Solving AI Tasks with ChatGPT and its Friends in HuggingFace ([paper](https://arxiv.org/abs/2303.17580), [code](https://github.com/microsoft/JARVIS)) - Using a LLM as brain, HuggingGPT identifies what HuggingFace models to use to solve tasks. Notably Microsoft is calling this `JARVIS`.
 
# Libraries / Tools

- [Github Copilot](https://github.com/features/copilot) - I use Copilot in my IDE, VS Code and it's dramatically improved my producitivity (10-20%?). More than that it makes coding less tedious and lowers the activiation energy for coding tasks. For example generating docstrings is trivial (and happens much more frequently!). And because the recommendations are inline, the developer's 'flow' is not broken. I also moved from Jupyter Notebooks in a browser to using Jupyter in VS Code. Radek Omulski has a [blog post](https://radekosmulski.com/an-ide-for-the-era-of-ai/) for how to set this up. I do plan to try [GenAI](https://github.com/noteable-io/genai) as well.
- [langchain](https://github.com/hwchase17/langchain) - Building applications with LLMs through composability
- [llama_index](https://github.com/jerryjliu/llama_index) - LlamaIndex (GPT Index) is a project that provides a central interface to connect your LLM's with external data.
- [GenAI](https://github.com/noteable-io/genai) - generative AI tooling for IPython
- [marvin](https://github.com/PrefectHQ/marvin) - Meet Marvin: a batteries-included library for building AI-powered software. Marvin's job is to integrate AI directly into your codebase by making it look and feel like any other function.


# Prompt Engineering

- [What is Prompt Engineering](https://prmpts.ai/blog/what-is-prompt-engineering) - like how Googling became a skill (aka "Google-fu"), I think Prompt Engineering is an important skill to develop
- [awesome-chatgpt-prompts](https://github.com/f/awesome-chatgpt-prompts) - A curated list of awesome ChatGPT prompts. I like "Act as a Linux Terminal" prompt.
- [Prompt Engineering Guide](https://github.com/dair-ai/Prompt-Engineering-Guide) - "Motivated by the high interest in developing with LLMs, we have created this new prompt engineering guide that contains all the latest papers, learning guides, lectures, references, and tools related to prompt engineering."

# Predictions

- 2023-04-01 - [@AllenDowney](https://mobile.twitter.com/AllenDowney) predicts "The great majority of coding will be LLM-assisted, starting now." ([tweet](https://mobile.twitter.com/AllenDowney/status/1642292405201190915), [blog](https://www.allendowney.com/blog/2023/04/02/llm-assisted-programming/))

